[package]
name = "stapifaction"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
stapifaction_derive = { optional = true, path = "../stapifaction_derive" }
serde = { version = "1.0" }
erased-serde = "0.3"

[features]
derive = ["stapifaction_derive"]
