[package]
name = "stapifaction_derive"
version = "0.1.0"
edition = "2021"

[lib]
name = "stapifaction_derive"
proc-macro = true


[dependencies]
proc-macro2 = "1.0"
syn = "2.0"
quote = "1.0"
darling = "0.20"
convert_case = "0.6"
itertools = "0.12"
